/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pri_weiqiang_tryit_jni_JNIUtils */

#ifndef _Included_pri_weiqiang_tryit_jni_JNIUtils
#define _Included_pri_weiqiang_tryit_jni_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pri_weiqiang_tryit_jni_JNIUtils
 * Method:    sayHelloFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pri_weiqiang_tryit_jni_JNIUtils_sayHelloFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
